# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

gems:
  - jekyll-sitemap

url: https://www.getdenied.com
name: Denied - Skip Terrible Music
title: Denied -
description: "Denied saves your ears from music you can't stand. Skip songs by artist, title or album."
keywords: spotify,skip,terrible,music,radio,playlist,next,itunes,remote,control,song,album,track,band,artist,filter,menu,disable
author:
  name: Boy van Amstel
  email: boy@dangercove.com
  twitter: "@deniedapp"
# price: $6.99
sale: false
  # price: $6.99
  # duration: ", only this week"
trial: false

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: false

permalink: /news/:title/

excerpt_separator: <!-- more -->

urls:
  update: https://update.getdenied.com
  download: /download
  # download: http://localhost:8888/Denied-v1.0.0.zip
  appstore: /appstore
  buy: /buy
  presskit: /presskit
  review: macappstore://itunes.apple.com/app/id909257784?mt=12

contact:
  email: hello@getdenied.com
  twitter: "@deniedapp"

analytics:
  GA:
    trackingID: UA-27275793-26
